#!/bin/bash
#Book Name: Cloud Native CI/CD with Tekton & ArgoCD
#Authors: Arunvel Arunachalam/ Ajay Arunachalam
#Purpose:  pipeline shared workspace

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: workspace-pipeline-ref
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
  - name: write-task
    taskRef:
      name: write-task
    workspaces:
      - name: shared-data
        workspace: pipeline-ws
  - name: read-task
    taskRef:
        name: read-task
    workspaces:
        - name: shared-data
          workspace: pipeline-ws
    runAfter: 
        - write-task