#!/bin/bash
#Book Name: Cloud Native CI/CD with Tekton & ArgoCD
#Authors: Arunvel Arunachalam/ Ajay Arunachalam
#Purpose: # Taskrun with parameters

apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: task2-run
spec:
  taskRef:
    name: task2
  params:
    - name: username
      value: "devops"
