apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  pipelineRef:
    name: git-clone-sonar-scan-build-push-deploy
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: sonar-source-pvc
    - name: docker-credentials
      secret:
        secretName: docker-credentials
    - name: kubeconfig-dir
      configMap:
        name: kubeconfig
    
  params:
    - name: repo-url
      value: "https://github.com/arunvel1988/appv1_docker"
    - name: image-reference
      value: arunvel1988/tekton-argocd1
