#!/bin/bash
#Book Name: Cloud Native CI/CD with Tekton & ArgoCD
#Authors: Arunvel Arunachalam/ Ajay Arunachalam
#Purpose: # secret to clone code from private repository

apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/git-0: https://github.com 
type: kubernetes.io/basic-auth
stringData:
  username: arunvel1988
  password: <use your github pat give limited privileges>